languageCode = "en-us"
title = "Joseph Earl"
baseURL = "https://www.josephearl.co.uk/"
theme = "cactus-plus"

[params]
    name = "Joseph Earl"
    description = "Joseph Earl`s Website"
    bio = "Senior Technologist @ThoughtWorks"
    twitter = "josephearl"
    enableRSS = false

    # Nav
    aboutLink = "http://about.me/josephearl"

    # Disqus commenting
    enableDisqus = false

    # Duoshuo commenting
    enableDuoshuo = false

    # GitHub issues
    enableGithubIssuesTips = false

    # Use description as title in single page, posts page and tags page.
    useDescriptionAsTitle = false

    # Google analytics
    enableGoogleAnalytics = false

    # Baidu analytics
    enableBaiduAnalytics = false

	# Choose a font for the social icons in the footer, either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
